### PR TITLE
Double ' to single

### PR DESCRIPTION
**Pull request by jhsoby**
Reported on https://translatewiki.net/wiki/Thread:Support/typo

### CODE REVIEW

**Comment by WPCleaner** [comment]
Thanks, but doubled single quotes prevent troubles with expansion of placeholders like "{0}". And the modification would need to be done on the Java source code, as the .pot file is generated automatically from it.

**Comment by jhsoby** [comment]
> Thanks, but doubled single quotes prevent troubles with expansion of placeholders like "{0}". 

Yeeah, that's not a good way to do it, for several reasons.
1. The double single quotes make the rest of the sentences appear in italics on Translatewiki (see e.g. https://translatewiki.net/wiki/Wikimedia:Wpcleaner-eca40d-The_error_hasn%27%27t_been_detecte/en )
2. How are translators supposed to know this? If somehow single single-quotes cause problems (I'm having a hard time understanding how they could interfere with {0} btw), they would also cause problems if they appear in translations, wouldn't they?
3. At least one language I know if (Neapolitan) uses double single-quotes as part of its orthography. How are translators supposed to enter that? Triple single-quotes? Quadruple single-quotes?

If single single-quotes are causing issues, why not escape them normally with \? That is handled gracefully by Translatewiki, as far as I know.

**Comment by WPCleaner** [comment]
I will try escaping single quotes with \' instead of doubling them. If it works the same for GNU gettext in Java mode and is better for Translatewiki, I will change them.

**Comment by WPCleaner** [comment]
[Task opened in Phabricator](https://phabricator.wikimedia.org/T259008).

**Pull request closed without merging**
